# Generated by Django 2.1 on 2019-10-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('base_offer', models.IntegerField(default=0)),
                ('min_pay', models.IntegerField(default=0)),
                ('mantis', models.TextField()),
                ('slack', models.TextField()),
                ('whatsapp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emp_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_uname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_name', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.IntegerField(choices=[(1, 'Permanent'), (2, 'Temporary'), (3, 'Contractor'), (4, 'Intern')], default=1)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user_active', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, max_length=13)),
                ('whatsapp', models.CharField(blank=True, max_length=13)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Not Specified')], default=3)),
                ('pay_type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Performance Based'), (3, 'Not Assigned')], default=3)),
                ('pay', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='users/images/default.jpg', upload_to='users/images')),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Works_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_on_dept', to='users.Department', to_field='name')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_emp_name', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='emp_position',
            name='position_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='users.Position', to_field='position_name'),
        ),
        migrations.AlterUniqueTogether(
            name='works_in',
            unique_together={('emp_name', 'dept_name')},
        ),
    ]
