# Generated by Django 2.1 on 2019-11-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pay_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Performance Based', 'Performance Based'), ('Not Assigned', 'Not Assigned')], default='Not Assigned', max_length=20),
        ),
    ]
