# Generated by Django 2.1 on 2019-11-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191101_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emp_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contractor', 'Contractor'), ('Intern', 'Intern')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Performance Based', 'Performance Based'), ('Not Assigned', 'Not Assigned')], max_length=20, null=True),
        ),
    ]
