# Generated by Django 2.1 on 2019-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProvisionalEmployeeMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('token', models.TextField()),
                ('offer_sent_by', models.CharField(max_length=50)),
                ('position_assigned', models.IntegerField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('position_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('pay', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('pay_type', models.IntegerField(choices=[(1, 'Fixed'), (2, 'Performance Based'), (3, 'Not Assigned')], default=3)),
                ('emp_type', models.IntegerField(choices=[(1, 'Permanent'), (2, 'Temporary'), (3, 'Contractor'), (4, 'Intern')], default=1)),
            ],
        ),
    ]
