# Generated by Django 2.1 on 2019-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newprovisionalemployeemail',
            name='position_assigned',
        ),
        migrations.AlterField(
            model_name='newprovisionalemployeemail',
            name='position_name',
            field=models.IntegerField(blank=True, choices=[(0, 'Manager'), (1, 'Developer'), (2, 'Tester'), (3, 'CEO')], null=True),
        ),
    ]
