# Generated by Django 2.1 on 2019-10-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191031_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newprovisionalemployeemail',
            old_name='user_name',
            new_name='username',
        ),
    ]
