# Generated by Django 2.1 on 2019-11-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191031_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprovisionalemployeemail',
            name='pay_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Performance Based', 'Performance Based'), ('Not Assigned', 'Not Assigned')], default='Not Assigned', max_length=20),
        ),
    ]
